name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t dsu-login-app .

      - name: Run Container
        run: docker run -d -p 3000:80 dsu-login-app